"""
Configuration for VSL Sentence Recognition project.
Adjust paths and hyperparameters before training.
"""
from pathlib import Path

# ── Paths ─────────────────────────────────────────────────────────────────────
ROOT_DIR         = Path(__file__).parent
SRC_DIR          = ROOT_DIR / 'src'

# Sentence video data
DATA_DIR         = ROOT_DIR / 'data' / 'sentence_videos'      # raw sentence videos
SEQUENCE_PATH    = ROOT_DIR / 'data' / 'sequences'            # extracted .npy files
LABEL_PATH       = ROOT_DIR / 'data' / 'labels.json'          # {video_name: "spoken sentence"}

# Word Model (from vsl-recognition)
WORD_MODEL_DIR      = ROOT_DIR.parent / 'vsl-recognition' / 'checkpoints'
WORD_MODEL_PATH     = WORD_MODEL_DIR / 'best_model'
WORD_SEQUENCE_PATH  = ROOT_DIR.parent / 'vsl-recognition' / 'data' / 'sequences'  # word .npy files
WORD_SEQUENCE_LENGTH= 33       # must match sequence_length used when training Word Model

# Dictionary (built from Word Model, saved here in vsl-sentence)
DICTIONARY_SAVE_PATH = ROOT_DIR / 'data' / 'attention_dictionary'
DICTIONARY_PATH      = DICTIONARY_SAVE_PATH / 'dictionary.npy'
ACTION_NAMES_PATH    = DICTIONARY_SAVE_PATH / 'action_names.json'

# Sentence Model checkpoints
CHECKPOINT_DIR   = ROOT_DIR / 'checkpoints'
LOGS_DIR         = ROOT_DIR / 'logs'
PSEUDO_LABEL_PATH= ROOT_DIR / 'data' / 'pseudo_labels.json'   # generated by pseudo_label.py

# ── Data Config ───────────────────────────────────────────────────────────────
SEQUENCE_LENGTH  = 200    # max frames for sentence (longer than word!)
KEYPOINT_DIM     = 1662   # mediapipe holistic keypoints

# Sliding window for pseudo-labeling
WINDOW_SIZE      = 30     # frames per window (same as word model sequence_length)
WINDOW_STRIDE    = 5      # stride between windows
CONFIDENCE_THRESH= 0.70   # min confidence to accept a gloss prediction

# ── Model Config ──────────────────────────────────────────────────────────────
# num_gloss is loaded dynamically from action_names.json
# +1 for CTC blank token (index 0)

MODEL_CONFIG = {
    'pose_dim':    132,
    'face_dim':    1404,
    'hand_dim':    126,
    'pose_units':  64,
    'face_units':  128,
    'hand_units':  64,
    'shared_units_1': 256,
    'shared_units_2': 128,
    'bilstm_units_1': 64,
    'bilstm_units_2': 32,
    'dropout':     0.3,
}

# ── Training Config ───────────────────────────────────────────────────────────
TRAINING_CONFIG = {
    'learning_rate':          1e-3,
    'finetune_learning_rate': 1e-4,   # used when loading pretrained word model weights
    'batch_size':             8,      # sentence videos are long → smaller batch
    'epochs':                 300,
    'early_stopping_patience': 20,
    'reduce_lr_patience':      10,
    'train_split':            0.80,
    'val_split':              0.10,
    # test = remaining 10%
    'lambda_distill':         0.1,    # weight for distillation loss
    'ctc_blank_index':        0,      # blank token is index 0
}
