"""Auto-generate the reproducibility environment table (review Issue 9).

Prints hardware, software versions, pose-side parameter counts and (if a
checkpoint is given) the measured seconds/epoch -> estimated training time.
Run on the SERVER so the reported environment is the one that trained the
models:

  python scripts/env_report.py --checkpoint /path/to/abl_ema50/checkpoint_last.pt
"""

from __future__ import annotations

import argparse
import platform
import sys
from pathlib import Path

sys.path.append(str(Path(__file__).resolve().parents[1]))

import torch

from src.models.pose_encoder import KeypointConformerEncoder


def optional_version(module_name: str) -> str:
    try:
        module = __import__(module_name)
        return getattr(module, "__version__", "installed (no __version__)")
    except ImportError:
        return "not installed in this env"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--checkpoint", type=Path,
                        help="a checkpoint_last.pt whose stored metrics give seconds/epoch")
    parser.add_argument("--epochs", type=int, default=50)
    args = parser.parse_args()

    rows: list[tuple[str, str]] = [
        ("Python", platform.python_version()),
        ("PyTorch", torch.__version__),
        ("CUDA (torch build)", str(torch.version.cuda)),
        ("cuDNN", str(torch.backends.cudnn.version())),
        ("Transformers", optional_version("transformers")),
        ("MediaPipe", optional_version("mediapipe")),
        ("NumPy", optional_version("numpy")),
        ("OS", platform.platform()),
    ]
    if torch.cuda.is_available():
        props = torch.cuda.get_device_properties(0)
        rows.append(("GPU", f"{props.name} ({props.total_memory / 2**30:.0f} GB)"))
    else:
        rows.append(("GPU", "none visible (run on the training server!)"))

    harp = KeypointConformerEncoder(model_dim=256, projection_dim=1024, num_layers=4,
                                    num_heads=4, hand_aware=True)
    uniform = KeypointConformerEncoder(model_dim=256, projection_dim=1024, num_layers=4,
                                       num_heads=4, hand_aware=False)
    count = lambda m: sum(p.numel() for p in m.parameters())
    rows.append(("Pose-side params (HARP / uniform)", f"{count(harp):,} / {count(uniform):,}"))

    if args.checkpoint and args.checkpoint.exists():
        state = torch.load(args.checkpoint, map_location="cpu", weights_only=False)
        train_metrics = state.get("metrics", {}).get("train", {})
        seconds = train_metrics.get("seconds")
        if seconds:
            rows.append(("Seconds / epoch (measured)", f"{seconds:,.0f}"))
            rows.append((f"Est. training time ({args.epochs} ep)",
                         f"{seconds * args.epochs / 3600:.1f} h"))
        rows.append(("Checkpoint epoch", str(state.get("epoch", "?"))))

    print("# Reproducibility environment (auto-generated by scripts/env_report.py)\n")
    print("| Item | Value |")
    print("|---|---|")
    for name, value in rows:
        print(f"| {name} | {value} |")


if __name__ == "__main__":
    main()
